import { useEffect, useState } from "react";
import { listen } from "@tauri-apps/api/event";
import { Check, CircleAlert, Download, FolderOpen, FolderPlus, Link2, Pencil, RefreshCw, Sparkles, Trash2, X } from "lucide-react";
import { ai, connectionName, providerNames, type ComputerSpecs, type Connection, type LibraryFile, type ModelLibrary, type Provider } from "./ai";

type Tab = "Your models" | "API" | "Local" | "Hugging Face";
type Browser = "api" | "server" | "library" | "repositories" | "files" | null;
type HfModel = { id: string };
type HfFile = { path: string; size: number };
const providers: Provider[] = ["groq", "openrouter", "google", "nvidia", "custom"];
const bytes = (value: number) => value ? `${(value / 1024 ** 3).toFixed(value > 10 * 1024 ** 3 ? 0 : 1)} GB` : "—";
const parameters = (value: string) => value.match(/(?:^|[-_ .])(\d+(?:\.\d+)?)([bm])(?:\b|[-_ .])/i)?.slice(1).join("").toUpperCase() ?? "";
const displayName = (name: string) => name.replace(/\.gguf$/i, "").replace(/[-_]+/g, " ").replace(/\bq\d[^ ]*/ig, "").replace(/\s+/g, " ").trim();

export function AISettings() {
  const [tab, setTab] = useState<Tab>("Your models"), [browser, setBrowser] = useState<Browser>(null);
  const [connections, setConnections] = useState<Connection[]>([]), [library, setLibrary] = useState<ModelLibrary>({ default_root: "", roots: [] }), [files, setFiles] = useState<LibraryFile[]>([]), [specs, setSpecs] = useState<ComputerSpecs | null>(null);
  const [provider, setProvider] = useState<Provider>("groq"), [key, setKey] = useState(""), [name, setName] = useState(""), [baseUrl, setBaseUrl] = useState(""), [trusted, setTrusted] = useState(false), [showKey, setShowKey] = useState(false), [models, setModels] = useState<string[]>([]), [model, setModel] = useState("");
  const [ollama, setOllama] = useState<{name:string;size:number}[]>([]), [localName, setLocalName] = useState("Local server"), [localUrl, setLocalUrl] = useState("http://127.0.0.1:1234/v1"), [localKey, setLocalKey] = useState(""), [localModels, setLocalModels] = useState<string[]>([]), [localModel, setLocalModel] = useState("");
  const [query, setQuery] = useState(""), [hfModels, setHfModels] = useState<HfModel[]>([]), [repository, setRepository] = useState(""), [hfFiles, setHfFiles] = useState<HfFile[]>([]), [hfFile, setHfFile] = useState(""), [destination, setDestination] = useState(""), [progress, setProgress] = useState<{stage:string;received:number;total?:number}|null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [status, setStatus] = useState("");
  const refresh = async () => { setConnections(await ai.connections()); setLibrary(await ai.library()); setFiles(await ai.libraryFiles()); setSpecs(await ai.computerSpecs()); };
  useEffect(() => { void refresh().catch((e) => setError(String(e))); }, []);
  useEffect(() => { if (tab === "Local") void ai.ollamaModels().then(setOllama).catch(() => setOllama([])); }, [tab]);
  useEffect(() => { let off: (() => void) | undefined; void listen<{stage:string;received:number;total?:number}>("lotus-hf-download", (event) => setProgress(event.payload)).then((value) => off = value); return () => off?.(); }, []);
  const run = async (work: () => Promise<void>) => { if (busy) return; setBusy(true); setError(""); setStatus(""); try { await work(); } catch (e) { setError(String(e)); } finally { setBusy(false); } };
  const chosen = connections.find((item) => item.provider === provider);
  const chooseProvider = (next: Provider) => { const saved = connections.find((item) => item.provider === next); setProvider(next); setName(saved?.name ?? ""); setBaseUrl(saved?.base_url ?? ""); setKey(""); setModels([]); setModel(saved?.model ?? ""); setTrusted(false); };
  const maxMemory = Math.max(specs?.available_ram_bytes ?? 0, ...(specs?.gpus.map((gpu) => gpu.vram_bytes) ?? [0]));
  const fits = (size:number) => size > 0 && maxMemory > 0 && size * 1.25 <= maxMemory * .72;
  const Fit = ({size}:{size:number}) => <span className={`model-fit ${fits(size) ? "fits" : ""}`} title={fits(size) ? "Likely to run on this computer" : "May need more available memory"}>{fits(size) ? <Check size={15}/> : <CircleAlert size={15}/>}</span>;
  const source = (c: Connection) => c.provider === "lotus" ? "Lotus runtime" : c.source === "ollama" ? "Ollama" : c.source === "local" ? "Local server" : "API";
  const chooseRoot = () => void run(async () => { const next = await ai.chooseModelRoot(); if (next) { setLibrary(next); await refresh(); setStatus("Default model folder selected."); }});
  const addRoot = () => void run(async () => { const next = await ai.addModelRoot(); if (next) { setLibrary(next); await refresh(); }});
  const manage = (file: LibraryFile, action: "reveal"|"rename"|"move"|"delete") => void run(async () => { if (action === "reveal") await ai.revealModel(file.path); if (action === "delete") { if (!window.confirm(`Delete ${file.name}? This permanently removes the model file.`)) return; await ai.deleteModel(file.path); } if (action === "rename") { const next = window.prompt("New .gguf filename", file.name); if (next && next !== file.name) await ai.renameModel(file.path, next); } if (action === "move") { const roots = library.roots.filter((root) => root !== file.root); const next = roots.length ? window.prompt(`Move to an approved folder:\n${roots.join("\n")}`, roots[0]) : null; if (next) await ai.moveModel(file.path, next); } await refresh(); });
  const runLotus = (file: LibraryFile) => void run(async () => { const loaded = await ai.runLotus(file.path); await refresh(); window.dispatchEvent(new Event("lotus-ai-settings")); setStatus(`${loaded} is running directly in Lotus and ready in Assistant.`); });
  const importOllamaAction = (file: LibraryFile) => void run(async () => { const suggested = file.name.replace(/\.gguf$/i, "").toLowerCase().replace(/[^a-z0-9._-]+/g, "-").slice(0,80); const runtimeName = window.prompt("Ollama model name", suggested); if (!runtimeName) return; const loaded = await ai.importOllama(file.path, runtimeName); await ai.saveOllama(loaded); await refresh(); window.dispatchEvent(new Event("lotus-ai-settings")); setStatus(`${loaded} is ready through Ollama.`); });
  const openRepo = (item:HfModel) => void run(async () => { setRepository(item.id); const next = await ai.hfFiles(item.id); setHfFiles(next); setHfFile(next[0]?.path ?? ""); setDestination(next[0]?.path.split("/").at(-1) ?? "model.gguf"); setBrowser("files"); });
  const browserTitle = browser === "api" ? "Provider models" : browser === "server" ? "Local server models" : browser === "library" ? "Model library" : browser === "repositories" ? "Hugging Face models" : "GGUF files";
  return <div className="ai-settings"><h3>AI models</h3>
    {specs ? <dl className="computer-specs"><div><dt>CPU</dt><dd>{specs.cpu} · {specs.cores} cores</dd></div><div><dt>Memory</dt><dd>{bytes(specs.available_ram_bytes)} free of {bytes(specs.ram_bytes)}</dd></div><div><dt>Graphics</dt><dd>{specs.gpus.length ? specs.gpus.map((gpu) => `${gpu.name} · ${bytes(gpu.vram_bytes)} VRAM`).join(" / ") : "Integrated graphics"}</dd></div><div><dt>Model storage</dt><dd>{bytes(specs.library_free_bytes)} free · {library.default_root || "Choose a folder"}</dd></div><div><dt>System</dt><dd>{specs.system}</dd></div></dl> : <p className="muted">Reading computer specifications…</p>}
    <nav className="ai-model-tabs" aria-label="AI model settings">{(["Your models", "API", "Local", "Hugging Face"] as Tab[]).map((value) => <button key={value} aria-current={tab===value ? "page" : undefined} onClick={() => {setTab(value);setBrowser(null);setError("");}}>{value}</button>)}</nav>
    {tab === "Your models" && <section><div className="ai-section-heading"><h4>Connected models</h4><button className="icon" title="Refresh" aria-label="Refresh models" onClick={() => void run(refresh)}><RefreshCw size={15}/></button></div>{connections.map((c) => <article className="ai-model-card" key={c.provider}><div><strong>{c.model}</strong><small>{source(c)} · {connectionName(c)}</small><small>{c.base_url}</small></div><div className="ai-card-actions"><span className="ai-connected">Connected</span><button title="Remove from Lotus" aria-label={`Remove ${c.model} from Lotus`} onClick={() => void run(async()=>{ await ai.remove(c.provider); await refresh(); window.dispatchEvent(new Event("lotus-ai-settings"));})}><Link2 size={14}/></button></div></article>)}{!connections.length && <p className="muted">No model connected yet.</p>}<h4 className="ai-installed-heading">Local library</h4><button onClick={() => {setBrowser("library");void refresh();}}>Browse {files.length} GGUF files</button></section>}
    {tab === "API" && <fieldset disabled={busy} className="ai-form"><label>Provider<select value={provider} onChange={(e)=>chooseProvider(e.target.value as Provider)}>{providers.map((item)=><option key={item} value={item}>{providerNames[item]}</option>)}</select></label>{provider === "custom" && <><label>Provider name<input value={name} onChange={(e)=>setName(e.target.value)} /></label><label>API base URL<input type="url" value={baseUrl} onChange={(e)=>{setBaseUrl(e.target.value);setKey("");}} /></label><label className="ai-consent"><input type="checkbox" checked={trusted} onChange={(e)=>setTrusted(e.target.checked)}/>I trust this endpoint.</label></>}<label>API key<div className="ai-key-field"><input type={showKey?"text":"password"} value={key} placeholder={chosen?"Key saved · leave blank to keep":"Paste API key"} onChange={(e)=>setKey(e.target.value)} /><button type="button" onClick={()=>setShowKey(!showKey)}>{showKey?"Hide":"Show"}</button></div></label><button onClick={()=>void run(async()=>{const next=await ai.models(provider,key,baseUrl);setModels(next);setModel(next[0]??"");setBrowser("api");})}>Load models</button><label>Model ID<input value={model} onChange={(e)=>setModel(e.target.value)} /></label><button className="primary" disabled={!model.trim()} onClick={()=>void run(async()=>{await ai.save(provider,key,model,name,baseUrl);await refresh();window.dispatchEvent(new Event("lotus-ai-settings"));setStatus("Connection saved securely.");})}>Test &amp; save</button></fieldset>}
    {tab === "Local" && <section className="ai-local"><div className="ai-section-heading"><div><h4>Model library</h4><p className="muted">Local GGUF files stay in folders you approve.</p></div><button className="icon" title="Rescan" aria-label="Rescan model folders" onClick={()=>void run(refresh)}><RefreshCw size={15}/></button></div><p className="settings-path">{library.default_root || "No default model folder selected"}</p><div className="ai-actions"><button onClick={chooseRoot}><FolderOpen size={15}/>Choose default folder</button><button onClick={addRoot}><FolderPlus size={15}/>Add folder</button><button onClick={()=>{setBrowser("library");void refresh();}}>Manage files</button></div><hr/><div className="ai-section-heading"><div><h4>Ollama (optional)</h4><p className="muted">Use models Ollama already runs.</p></div><button className="icon" title="Refresh Ollama" aria-label="Refresh Ollama" onClick={()=>void run(async()=>setOllama(await ai.ollamaModels()))}><RefreshCw size={15}/></button></div>{ollama.map((item)=><article className="ai-model-card" key={item.name}><div><strong>{item.name}</strong><small>{bytes(item.size)}</small></div><button onClick={()=>void run(async()=>{await ai.saveOllama(item.name);await refresh();window.dispatchEvent(new Event("lotus-ai-settings"));})}>Use in Assistant</button></article>)}<hr/><h4>Compatible local server</h4><p className="muted">Connect LM Studio or another local OpenAI-compatible server.</p><fieldset disabled={busy} className="ai-form"><label>Name<input value={localName} onChange={(e)=>setLocalName(e.target.value)} /></label><label>Local API base URL<input value={localUrl} onChange={(e)=>setLocalUrl(e.target.value)} /></label><label>Optional API key<input type="password" value={localKey} onChange={(e)=>setLocalKey(e.target.value)} /></label><button onClick={()=>void run(async()=>{const next=await ai.models("local",localKey,localUrl);setLocalModels(next);setLocalModel(next[0]??"");setBrowser("server");})}>Find models</button><label>Model ID<input value={localModel} onChange={(e)=>setLocalModel(e.target.value)} /></label><button className="primary" disabled={!localModel} onClick={()=>void run(async()=>{await ai.save("local",localKey,localModel,localName,localUrl);await refresh();window.dispatchEvent(new Event("lotus-ai-settings"));})}>Test &amp; connect</button></fieldset></section>}
    {tab === "Hugging Face" && <section><h4>Download a public GGUF model</h4><p className="muted">Browse the public GGUF catalogue. Downloads go directly to your model folder.</p>{!library.default_root && <button onClick={chooseRoot}>Choose a model folder first</button>}<div className="ai-search-row"><input value={query} placeholder="Search public GGUF models…" onChange={(e)=>setQuery(e.target.value)} /><button disabled={busy} onClick={()=>void run(async()=>{setHfModels(await ai.hfSearch(query));setBrowser("repositories");})}>{query.trim()?"Search":"Browse models"}</button></div>{progress && <p role="status">{progress.stage}{progress.total?` · ${bytes(progress.received)} of ${bytes(progress.total)}`:""}</p>}{progress?.stage === "Downloading" && <button onClick={()=>void ai.hfCancel()}>Cancel download</button>}</section>}
    {status && <p role="status">{status}</p>}{error && <p role="alert" className="ai-error">{error}</p>}
    {browser && <aside className="model-browser" aria-label={browserTitle}><header><strong>{browserTitle}</strong><button className="icon" aria-label="Close model browser" onClick={()=>setBrowser(null)}><X size={16}/></button></header>{browser === "api" && <div className="model-browser-list">{models.map((item)=><button key={item} className={model===item?"selected":""} onClick={()=>{setModel(item);setBrowser(null);}}>{item}</button>)}</div>}{browser === "server" && <div className="model-browser-list">{localModels.map((item)=><button key={item} className={localModel===item?"selected":""} onClick={()=>{setLocalModel(item);setBrowser(null);}}>{item}</button>)}</div>}{browser === "repositories" && <div className="model-browser-list">{hfModels.map((item)=><button key={item.id} onClick={()=>openRepo(item)}><span className="model-fit"><CircleAlert size={15}/></span><span><strong>{item.id}</strong>{parameters(item.id) && <small>{parameters(item.id)} parameters</small>}</span></button>)}</div>}{browser === "files" && <div className="model-browser-list">{hfFiles.map((item)=><button key={item.path} className={hfFile===item.path?"selected":""} onClick={()=>{setHfFile(item.path);setDestination(item.path.split("/").at(-1)??"model.gguf");}}><Fit size={item.size}/><span><strong>{item.path}</strong><small>{bytes(item.size)}{parameters(item.path) ? ` · ${parameters(item.path)} parameters` : ""}</small></span></button>)}{hfFile && <div className="model-download"><label>Filename<input value={destination} onChange={(e)=>setDestination(e.target.value)} /></label><button className="primary" disabled={busy||!library.default_root} onClick={()=>void run(async()=>{setProgress({stage:"Starting…",received:0});await ai.hfDownload(repository,hfFile,destination);await refresh();setStatus("GGUF model downloaded to your library.");})}><Download size={15}/>Download</button></div>}</div>}{browser === "library" && <div className="model-browser-list">{files.map((file)=><article key={file.path} className="library-file"><div className="library-file-title"><Fit size={file.size}/><span><strong>{displayName(file.name)}</strong><small>{bytes(file.size)}{parameters(file.name) ? ` · ${parameters(file.name)} parameters` : ""}</small></span></div><div><button className="library-load" title="Run directly in Lotus" onClick={()=>runLotus(file)}><Sparkles size={14}/>Run in Lotus</button><button title="Use through Ollama" onClick={()=>importOllamaAction(file)}>Ollama</button><button title="Reveal in File Explorer" onClick={()=>manage(file,"reveal")}><FolderOpen size={14}/></button><button title="Rename model" onClick={()=>manage(file,"rename")}><Pencil size={14}/></button><button title="Move model" onClick={()=>manage(file,"move")}><FolderPlus size={14}/></button><button className="danger-icon" title="Delete model" onClick={()=>manage(file,"delete")}><Trash2 size={14}/></button></div></article>)}</div>}</aside>}
  </div>;
}
